# Generated by Django 2.1.7 on 2019-05-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbm', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=1)),
                ('img1', models.CharField(max_length=64)),
                ('img2', models.CharField(max_length=64)),
                ('img3', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceInfo',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('bssid', models.CharField(max_length=20)),
                ('attendance_start_time', models.DateTimeField()),
                ('attendance_end_time', models.DateTimeField(null=True)),
                ('attendance_tag', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='choose_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseNum', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher2Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('teacherNum', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('teacherName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('studentNum', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('img1', models.CharField(max_length=64)),
                ('img2', models.CharField(max_length=64)),
                ('img3', models.CharField(max_length=64)),
                ('img4', models.CharField(max_length=64)),
                ('img5', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='teacher2course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='choose_course',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourseInfo'),
        ),
        migrations.AddField(
            model_name='choose_course',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
        migrations.AddField(
            model_name='choose_course',
            name='teac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourseInfo'),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AttendanceInfo'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher2course',
            unique_together={('course_id', 'teacher_id')},
        ),
        migrations.AlterUniqueTogether(
            name='choose_course',
            unique_together={('stu', 'teac', 'cour')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('stu', 'att')},
        ),
    ]
