# Generated by Django 2.1.7 on 2019-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='complain_tag',
            field=models.CharField(default=2, max_length=1),
        ),
    ]
