# Generated by Django 2.1.7 on 2019-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendance_complain_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='img1',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='img2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='img3',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
