# Generated by Django 2.1.7 on 2019-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190504_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='img1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='img2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='img3',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
