# Generated by Django 2.1.7 on 2019-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190504_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='complain_tag',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img2',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img3',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img4',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img5',
            field=models.CharField(max_length=128),
        ),
    ]
