# Generated by Django 2.1.7 on 2019-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190524_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='complain_text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
